version: "3.7"

networks:
  projeto-getapet:
    driver: bridge

volumes:
  volume-getapet:

services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - projeto-getapet

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - projeto-getapet
    volumes:
      - volume-getapet:/data/db

